// src/components/Admissions/Departments.js
export const departments = [
  "ELECTRONICS AND COMMUNICATION ENGINEERING",
  "CIVIL ENGINEERING",
  "COMPUTER SCIENCE & ENGINEERING",
  "COMPUTER APPLICATIONS",
  "HUMANITIES AND APPLIED SCIENCE",
  "MANAGEMENT STUDIES",
  "MECHANICAL ENGINEERING"
];
