// src/components/Admissions/Departments.js
export const departments = [
  "ELECTRONICS AND COMMUNICATION ENGINEERING",
  "ARTIFICIAL INTELLIGENCE",
  "ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING",
  "COMPUTER SCIENCE & ENGINEERING",
  "COMPUTER APPLICATIONS",
  "HUMANITIES AND APPLIED SCIENCE",
  "MANAGEMENT STUDIES",
  "MECHANICAL ENGINEERING",
  "ELECTRICAL ENGINEERING",
];
