export const states = [
    "Andaman and Nicobar Islands",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Delhi",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Ladakh",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Puducherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
];

export const institutes = [
    "RIME (B.Tech, MBA, MCA)",
    "RIME (BBA, BCA)",
    "RIME (B.ED, M.ED)",
];

export const courses = [
    "B.Tech (CSE)",
    "B.Tech (CSE-AI)",
    "B.Tech (CSE-AIML)",
    "B.Tech - Mechanical Engineering (ME)",
    "B.Tech - Electrical Engineering (EE)",
    "Bachelor of Business Administration (BBA)",
    "Bachelor of Computer Applications (BCA)",
    "Master of Business Administration (MBA)",
    "Master of Computer Applications (MCA)",
    "Bachelor of Education (B.Ed)",
    "Master of Education (M.Ed)",
]
